name : CI Pipeline

on :
  push:
    branches:
      - main


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "PORT=5000" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=notesdb" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for the app to be ready
        run: sleep 10
        
      - name: Test health check
        run: curl http://localhost:5000/health

      - name: Shut down containers
        run: docker compose down